"""empty message

Revision ID: 21b506e6cf10
Revises: b236fc73330
Create Date: 2014-11-02 11:42:41.368682

"""

# revision identifiers, used by Alembic.
revision = '21b506e6cf10'
down_revision = 'b236fc73330'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'download_tag', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'download_tag')
    ### end Alembic commands ###
