"""empty message

Revision ID: 296f140e113b
Revises: 48960b8ea815
Create Date: 2014-10-25 16:07:18.895256

"""

# revision identifiers, used by Alembic.
revision = '296f140e113b'
down_revision = '48960b8ea815'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('event', sa.String(length=128), nullable=True))
    op.add_column('timeslot', sa.Column('votable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeslot', 'votable')
    op.drop_column('timeslot', 'event')
    ### end Alembic commands ###
