"""empty message

Revision ID: 2abb1d002d34
Revises: 43a4727a4c8d
Create Date: 2014-10-29 09:12:15.256836

"""

# revision identifiers, used by Alembic.
revision = '2abb1d002d34'
down_revision = '43a4727a4c8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_file', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_file', 'description')
    ### end Alembic commands ###
