"""empty message

Revision ID: 43a4727a4c8d
Revises: fcfdb15d3b
Create Date: 2014-10-28 10:13:41.331704

"""

# revision identifiers, used by Alembic.
revision = '43a4727a4c8d'
down_revision = 'fcfdb15d3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downloads_tagged',
    sa.Column('download_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['download_id'], ['download_file.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['download_tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downloads_tagged')
    op.drop_table('download_file')
    op.drop_table('download_tag')
    ### end Alembic commands ###
