"""empty message

Revision ID: 4463f03d45e0
Revises: 5180b2879899
Create Date: 2014-10-27 20:35:39.194451

"""

# revision identifiers, used by Alembic.
revision = '4463f03d45e0'
down_revision = '5180b2879899'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_request')
    ### end Alembic commands ###
