"""empty message

Revision ID: 5180b2879899
Revises: 24394b382fef
Create Date: 2014-10-25 18:21:44.906615

"""

# revision identifiers, used by Alembic.
revision = '5180b2879899'
down_revision = '24394b382fef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['timeslot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_vote')
    ### end Alembic commands ###
