"""empty message

Revision ID: 521338a7e3f0
Revises: 4463f03d45e0
Create Date: 2014-10-28 08:17:48.925840

"""

# revision identifiers, used by Alembic.
revision = '521338a7e3f0'
down_revision = '4463f03d45e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_request', sa.Column('played', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_request', 'played')
    ### end Alembic commands ###
