"""empty message

Revision ID: 56a649fc8ef8
Revises: 2abb1d002d34
Create Date: 2014-11-02 11:10:12.533669

"""

# revision identifiers, used by Alembic.
revision = '56a649fc8ef8'
down_revision = '2abb1d002d34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
