"""empty message

Revision ID: b236fc73330
Revises: 56a649fc8ef8
Create Date: 2014-11-02 11:15:17.993465

"""

# revision identifiers, used by Alembic.
revision = 'b236fc73330'
down_revision = '56a649fc8ef8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
