"""empty message

Revision ID: fcfdb15d3b
Revises: 521338a7e3f0
Create Date: 2014-10-28 10:13:07.076618

"""

# revision identifiers, used by Alembic.
revision = 'fcfdb15d3b'
down_revision = '521338a7e3f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
